name: astro
channels:
  - defaults
  - conda-forge
  - astropy
  - tboch
  - vpython
dependencies:
# core packages
  - python
# packages used widely
  - matplotlib
  - numpy
  - scipy
  - pandas
  - astropy
  - sympy
  - astroquery
# packages used in a single notebook
  - altair
  - aplpy
  - bokeh
  - cufflinks-py
  - dask
  - h5py
  - hdf5
  - healpy
  - ipyaladin
  - plotly
  - pytables
  - pythreejs
  - seaborn
  - vaex
  - vaex-astro
  - vega
  - vispy
# vpython also needs a different Jupyter kernel 
# so using it in MyBinder may be more trouble than it's worth
#  - vpython
#
# some packages need pip, not conda
  - pip:
    - nbgitpuller
    - astroml
